### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by N0153128** [Transfusion/durararobot#10]
` File "/home/durararobot-alpha/bot.py", line 251, in login
    if resp_parsed['message'] == 'ok':
KeyError: 'message'`

**Comment by nobodyzxc** [comment]
what command you typed?
more info please

**Comment by zeosmar** [comment]
I got the same error msg. It happens right after "login default" command. There's no key 'message' in the resp_parsed variable:
`Traceback (most recent call last):
  File "/home/durararobot/bot.py", line 462, in cmdloop_with_keyboard_interrupt
    self.cmdloop()
  File "/home/anaconda3/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/anaconda3/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/durararobot/bot.py", line 374, in do_login
    self.bot.login(arg_split[0])
  File "/home/durararobot/bot.py", line 257, in login
    if resp_parsed['message'] == 'ok':
KeyError: 'message'`

**Comment by dandingol03** [comment]
i use ``login default``,same error

**Comment by nobodyzxc** [comment]
The value `use_https` in sample_config.ini generated by config_mgr.py is `False`,
change it to `True` and rename the sample_config.ini to config.ini would solve the problem.
